### ISSUE TITLE
Can't write in the Available Bangs searchbox

### ISSUE THREAD

**Issue by serovar** [sophie-glk/bang#13]
If I try to write to it, it search for the words I type in the page.
I tried it on Windows 10 and Fedora Linux, with Firefox 71 stable.

**Comment by sophie-glk** [comment]
Sorry I don't really understand what exactly the issue is. What do you mean by "Bangs searchbox"? Which website? Maybe you could elaborate further or post some screenshots?

**Comment by serovar** [comment]
Sorry, I am stupid, I confused your addon with another similar one xD
