### ISSUE TITLE
I'm feeling lucky support

### ISSUE THREAD

**Issue by filyp** [sophie-glk/bang#16]
In DDG, you can use `\` to go straight to the first search result, for example
```
\yt starless king
```
to open first search result on youtube of `starless king`

Or add ` !` at the end, for example
```
black hole !
```

It would be quite useful, especially the `\`

**Comment by babastienne** [comment]
I'm not a big fan of the idea to add a '!' character at the end of the search string. But i love the idea of implementing the `\` feature.

To be honest I didn't even knew it existed, but I already love it.

But it seems kind of hard to implement ...

**Comment by sophie-glk** [comment]
Will have to look into it, but it doesnt sound that easy to implement tbh. The easiest but hacky way of doing this is would be to just let ddg itself handle the request in the background.

**Comment by sophie-glk** [comment]
I have looked into it a bit more, and it seems to be out of scope for this project. DDG basically just searchs through the bang website and delivers the first result back to you. Not really something that we can accomplish.

**Comment by babastienne** [comment]
Unfortunatelly, even if I really wanted to see this feature it doesn't really surprise me. It was looking hard to accomplish.

**Comment by retdop** [comment]
Sorry to resuscitate a closed issue, but I really like the `!` feature in ddg. I find it super useful to get directly to an obvious result to a search query (especially for code documentation). 

From what I understood of the repo, it should be easier to implement than the `\` feature, as we could just redirect to ddg's request. 

For instance, the query `pandas to_dict !` would just be an alias for `!ddg pandas to_dict !`. 

What do you think?

**Comment by domportera** [comment]
> Sorry to resuscitate a closed issue, but I really like the `!` feature in ddg. I find it super useful to get directly to an obvious result to a search query (especially for code documentation).
> 
> From what I understood of the repo, it should be easier to implement than the `\` feature, as we could just redirect to ddg's request.
> 
> For instance, the query `pandas to_dict !` would just be an alias for `!ddg pandas to_dict !`.
> 
> What do you think?

agreed, though i see that it would violate how this project works. I've noticed this extension is *much* faster than DDG because it bypasses DDG altogether, which is great, but this proposed solution (which I ultimately support and would like very much) violates that approach.
