### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by nicolasmaia** [sophie-glk/bang#19]
It'd be super useful to have this add-on also usable on mobile.

**Comment by sophie-glk** [comment]
I will look into it when I release the next version with the new bug fixes to the firefox store

**Comment by sophie-glk** [comment]
I think its a restriction on the firefox side. Non mozilla selected addons should be installed this way: https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/

**Comment by Visne** [comment]
Any chance this addon would ever be accepted by Mozilla? Have also been wanting this, but I will try the workaround.

**Comment by Visne** [comment]
I guess it would be easier to wait for Firefox to allow all addons for the stable version. Annoying.
