### ISSUE TITLE
Beta feature with custom search engine not working

### ISSUE THREAD

**Issue by babastienne** [sophie-glk/bang#2]
While testing the last version of the module (currently on the master branch), I noticed that you added a new Beta feature.

While trying to use it, an error message was displayed saying that Firefox was unable to locate the search plugin. 
Those links seems to be dead because the return a 404 error : 
- https://tt7753.github.io/bang-custom-search/xml/plugin/startpage.xml
- https://tt7753.github.io/bang-custom-search/xml/plugin/google.xml
- https://tt7753.github.io/bang-custom-search/xml/plugin/ecosia.xml
- https://tt7753.github.io/bang-custom-search/xml/plugin/bing.xml

**Comment by sophie-glk** [comment]
Feature is no longer required and has been removed. Therefore i will close this issue.
