### ISSUE TITLE
Different behaviour from DuckDuckGo when no whitespace before !

### ISSUE THREAD

**Issue by Visne** [sophie-glk/bang#21]
In DuckDuckGo, when searching `abc!b` it would search "abc" using Bing. This addon however just searches `abc!b` in the default search engine. I can see how this could be considered a feature, but in my opinion its mildly annoying as I am used to how DuckDuckGo works, and I often carelessly put no space before the !. I my opinion, it would make sense if this addon would emulate DuckDuckGo as closely as possible.

**Comment by sophie-glk** [comment]
I added this to the latest development version. It would be great if you could try it out!

**Comment by Visne** [comment]
With the development version bangs don't seem to be working at all, yet I think the addon is installed correctly because "startpage.js loaded" is printed to the console.
