### ISSUE TITLE
urls in search query (such as for the wayback machine) do not work

### ISSUE THREAD

**Issue by aekaisato** [sophie-glk/bang#22]
When searching a URL with DuckDuckGo, for example using the Wayback Machine, the URL is converted back into regular plaintext (the url of the search as an example would be https://web.archive.org/web/*/https://www.startpage.com/). Using this extension, the text is still URI encoded, instead searching https://web.archive.org/web/*/https%3A%2F%2Fwww.startpage.com%2F which does not work properly as a search.

**Comment by babastienne** [comment]
Could you give an example of your problem ?
I cannot reproduce your issue.

Steps that I tried to reproduce : 
- Going to DDG (on chrome and firefox)
- Typing in the search bar : `!wbm http://google.com`
- It redirects me to `https://duckduckgo.com/?q=%21wbm+http%3A%2F%2Fgoogle.com&va=b&t=hc`
- Which finally redirects me to `https://web.archive.org/web/*/http%3A%2F%2Fgoogle.com`

I tried the same steps with the extension on firefox and got the same result : the URI is not encoded in both ways.

If you could give more information it would be great (steps to reproduce the issue, version of browser, version of the addon).

**Comment by aekaisato** [comment]
Yeah, sorry about the lack of info. I'm currently on Firefox 90.0.2 on EndeavourOS/Arch. I used !wayback in DuckDuckGo, which works as intended. (Strangely, !wayback works but !wbm doesn't).

Steps to reproduce:
  - Install this extension
  - Go to startpage.com
  - enter "!wayback https://google.com"

Steps to intended result (using DuckDuckGo):
  - Go to duckduckgo.com
  - enter "!wayback https://google.com"
