### ISSUE TITLE
custom bang does not work

### ISSUE THREAD

**Issue by vuthanho** [sophie-glk/bang#29]
Custom bang just performs a duckduckgo query with "!custom_bang @search@"

**Comment by sophie-glk** [comment]
Can you show me how your custom bang page looks like and tell me what version of the addon you are using? Because for me its working fine.

**Comment by vuthanho** [comment]
Nevermind, now it's working. I think it's because I was not granting full permissions (only to https://duckduckgo.com), as I was only looking for the custom bang feature of the extension.
