### ISSUE TITLE
Annoying notification dot is displayed

### ISSUE THREAD

**Issue by kulmegil** [sophie-glk/bang#30]
On any site Firefox displays annoying notification dot - both inside extensions menu and on toolbar.

Annoying notification dot is displayed on all tabs for any site - aside from sites extension has specifically requested permissions (Google, Bing, ect).

Clicking extension will make it disappear temporary - it will show up on page (re)load.

Dot on toolbar:
![Notification Dot 1](https://github.com/sophie-glk/bang/assets/570575/5351e42c-6ab7-42c4-8cee-c52f769e2e72)

Dot in unified extensions menu:
![Notification Dot 2](https://github.com/sophie-glk/bang/assets/570575/925bed51-26af-4df8-a6bd-d8ed0b7f4225)

**Comment by sophie-glk** [comment]
This was probably caused, because i forgot to remove the unnecessary permission "activeTab", it would be great if you could tell me if everything works as expected now.

**Comment by babastienne** [comment]
@sophie-glk seems fine. I could reproduce the bug before and with the lastest version of your code it's working well, I don't have the notification dot anymore. You'll need to publish a new version of the app on the store though for the update to be available for everyone.

**Comment by sophie-glk** [comment]
The new version should now be live.

**Comment by babastienne** [comment]
Yes, I confirm that it's ok with the latest online version. Thanks for your quick fix. :pray:

**Comment by kulmegil** [comment]
I can confirm it's working fine now. 

I didn't even noticed when extension updated in the background and was wandering what did I do to make that dot gone ;)
