### ISSUE TITLE
"De Mauro Dictionary" bangs do not work

### ISSUE THREAD

**Issue by serovar** [sophie-glk/bang#7]
!dit and !demauro should search for words in the Internazionale De Mauro dictionary, and they works fine on DuckDuckGo, but they give a "404 page not found" error when used through the addon.

**Comment by babastienne** [comment]
The bangs `!dit` and `!demauro` are not working anymore on Duckduckgo. I got a 404 error too when trying them with duckduckgo as my search engine.

However you can still add it to the extension if you want. You need to add `dit demauro` as bang and `https://www.internazionale.it/search/@search@` as the associated research. I just tried and it works.

A screen of my configuration showing the solution to you 2 issues :
![image](https://user-images.githubusercontent.com/16348048/65605466-6e081000-dfa9-11e9-8d8e-ee8deba8959d.png)

**Comment by serovar** [comment]
Thanks, I will configure them manually, but they work fine for me on DuckDuckGo though.

**Comment by serovar** [comment]
Related to [this](https://github.com/sophie-glk/bang/issues/6)
