### ISSUE TITLE
[Feature Request] Add backup/restore of custom bangs

### ISSUE THREAD

**Issue by serovar** [sophie-glk/bang#8]

**Comment by sophie-glk** [comment]
We could add an option to export to and load from a json file.

**Comment by sophie-glk** [comment]
I have added this feature with the latest commit to the development branch. Maybe you could test if it works as expected?

**Comment by serovar** [comment]
Sure, how can I install the development version?

**Comment by sophie-glk** [comment]
Switch the branch from master to develop and click on "download as zip". Extract the zip file somewhere, open: about:debugging#/runtime/this-firefox in firefox, click on load temporary addon and navigate to the manifest.json file that is in the downloaded plugin folder.

**Comment by serovar** [comment]
Thanks for the instructions, it seems to work fine!
